In [4]:
import pandas as pd
import numpy as np
import nltk

In [5]:
df=pd.read_csv(r"D:\Dig\SMSSpamCollection",sep="\t",names=['Label','Message'])
df.head()

Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Label    5572 non-null   object
 1   Message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


### Data Clelaning and Data Preprocessing

In [7]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

PS = PorterStemmer()
corpus = []

for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['Message'][i])
    review = review.lower()
    review = review.split()
    
    review = [PS.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

# Creating the bag of words model

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=25000)
X = cv.fit_transform(corpus).toarray()

### Creating Dummies

In [5]:
y = pd.get_dummies(df['Label'])
y = y.iloc[:,1].values

### Train Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

### Training mode

In [7]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [8]:
pred = model.predict(X_test)
pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

### Performace Mxtrix

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

0.979372197309417
[[940  15]
 [  8 152]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       955
           1       0.91      0.95      0.93       160

    accuracy                           0.98      1115
   macro avg       0.95      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115



<br>
____________________________________________________________________________________________________________________________

# Using Lemmatization

In [20]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()
# PS = PorterStemmer()
corpus = []

for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['Message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lem.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
    

# Creating the bag of words model

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X1 = tfidf.fit_transform(corpus).toarray()

In [21]:
y1 = pd.get_dummies(df['Label'])
y1 = y1.iloc[:,1].values

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1,y1,test_size=0.2,random_state=0)

In [23]:
from sklearn.naive_bayes import MultinomialNB

model1 = MultinomialNB()
model1.fit(X_train,y_train)

MultinomialNB()

In [24]:
pred1 = model1.predict(X_test)
pred1

array([0, 0, 0, ..., 0, 1, 0], dtype=uint8)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, pred1))
print(confusion_matrix(y_test, pred1))
print(classification_report(y_test, pred1))

0.9721973094170404
[[955   0]
 [ 31 129]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       955
           1       1.00      0.81      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115

